add drm-hotplug
radxa-pkg/rockchip-prebuilt pull request #4
Opened 2024-04-15 10:09 UTC by Ken-Vamrs

2024-04-15 10:16 UTC, RadxaYuntian requested changes

2024-04-15 10:16 UTC, RadxaYuntian commented on debian/rockchip-udev.install
> +man/drm-hotplug.8 /usr/share/man/man8
缺少结尾空行

2024-04-15 10:47 UTC, Ken-Vamrs commented on debian/rockchip-udev.install
> +man/drm-hotplug.8 /usr/share/man/man8
已修改

2024-04-15 11:14 UTC, RadxaYuntian commented on debian/rockchip-udev.install
> +man/drm-hotplug.8 /usr/share/man/man8
直接在github pr页面上点击re-request review，这样我的github通知页面也能列出来

2024-04-15 11:14 UTC, RadxaYuntian approved these changes

2024-04-16 07:23 UTC, RadxaYuntian requested changes
CI失败了，你修改一下[.pre-commit-config.yaml](https://github.com/radxa-pkg/rockchip-prebuilt/blob/main/.pre-commit-config.yaml)来忽略Rockchip的脚本吧：
https://pre-commit.com/#regular-expressions

2024-04-16 07:40 UTC, RadxaYuntian requested changes
rebase合并一下提交

2024-04-16 07:43 UTC, Ken-Vamrs commented
> rebase合并一下提交

三个合并成一个吗

2024-04-16 07:50 UTC, RadxaYuntian approved these changes

2024-04-17 02:02 UTC, merged